### ISSUE TITLE
Advice for knex-serverless-postgres

### ISSUE THREAD

**Issue by rswlkr** [MatissJanis/knex-serverless-mysql#1]
Hi @MatissJanis 

I'm trying to do a similar thing for the serverless-postgres package, is it just a case of adapting the dialect to suit? 

Cheers,
Ross

**Comment by MatissJanis** [comment]
Hey,

Yea, in the case of `serverless-mysql`, it was just the matter of adapting the interfaces. You can take a look at the implementation in this package. It's pretty minimal. :)

In terms of `serverless-postgres` - it _migth_ be just as simple. Though I have never used it, so can't guarantee.
